language: python
python:
  - "3.8"

before_install:
  - pip install poetry
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g eclint

install:
  - poetry install

script:
  - flake8 .
  - eclint check *.py sites/*.py
  - leech --help
  - python3 ebook/cover.py && file -E output.png && rm output.png
  - poetry build
  - ls -og dist/*
